# Generated by Django 4.2.6 on 2023-11-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_orderdetails_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='quantity',
            new_name='amount',
        ),
    ]
